/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'language' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const ConversationSession = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'createSession' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateResponse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getImageMetadata' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSessions' : IDL.Func([], [IDL.Vec(ConversationSession)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'language' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const ConversationSession = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'createSession' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateResponse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getImageMetadata' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSessions' : IDL.Func([], [IDL.Vec(ConversationSession)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };